# ms-runners deployment 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-messaging-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-messaging
  template:
    metadata:
      labels:
        app: ms-messaging
        env: prod
    spec:
      containers:
      - name: th-prj-ms-messaging
        image: paoloacqua/th-prj-ms-messaging:0.0.1
        resources:
          requests:
            memory: "400Mi"
            cpu: "80m"
          limits:
            memory: "410Mi"
            cpu: "90m"
        env:
          - name: SPRING_PROFILES_ACTIVE
            valueFrom:
              configMapKeyRef:
                name: ms-runners-config
                key: springProfile     
          - name: MySqlIp
            valueFrom:
              configMapKeyRef:
                name: ms-runners-config
                key: MySqlIp
        ports:
          - name: service
            containerPort: 5063
            protocol: TCP