# Mysql deployment 
# POD: mysql
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
        env: prod
    spec:
      containers:
      - image: mysql:8.0.30@sha256:eeabfa5cd6a2091bf35eb9eae6ae48aab8231fd760f5a61cd0129df454333b1d
        name: mysql
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: 20210821Ta!
        resources:
          requests:
            memory: "450Mi"
            cpu: "150m"
          limits:
            memory: "460Mi"
            cpu: "160m"
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
        ports:
        - containerPort: 3306
          protocol: TCP
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: th-prj-db-pvc