# ZUUL deployment 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zuul-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zuul
  template:
    metadata:
      labels:
        app: zuul
        env: prod
    spec:
      containers:
      - name: ms-zuul
        image: paoloacqua/th-prj-ms-zuul:0.2.0
        imagePullPolicy: Always
        resources:
          requests:
            memory: "300Mi"
            cpu: "150m"
          limits:
            memory: "350Mi"
            cpu: "160m"
        env:
          - name: SPRING_PROFILES_ACTIVE
            valueFrom:
              configMapKeyRef:
                name: ms-zuul-config
                key: springProfile
          - name: MsUserIp
            valueFrom:
              configMapKeyRef:
                name: ms-zuul-config
                key: MsUserIp  
          - name: MsAssociationsIp
            valueFrom:
              configMapKeyRef:
                name: ms-zuul-config
                key: MsAssociationsIp  
          - name: MsRunnersIp
            valueFrom:
              configMapKeyRef:
                name: ms-zuul-config
                key: MsRunnersIp  
          - name: MsRunningsIp
            valueFrom:
              configMapKeyRef:
                name: ms-zuul-config
                key: MsRunningsIp  
        ports:
          - name: service
            containerPort: 8120
            protocol: TCP