apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: th-prj-db-pvc
spec:
  resources:
    requests:
      storage: 10Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: "" # Tale property definisce il tipo di storage sottostante influsice quindi sulle prestazioni di I/O